name: build-and-test

on:
  push:
  pull_request:
  workflow_dispatch: # allows you to trigger manually
  schedule:
    - cron: '35 4 * * TUE' # Tuesday at 04:35 UTC”

jobs:
  build-and-test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      fail-fast: false
      matrix:
        # python-version: ['3.7', '3.8', '3.9', '3.10']
        python-version: ['3.7', '3.10']  # temporary.. to speed up testing
        # os: [Ubuntu, macOS, Windows]
        os: [Ubuntu, Windows]
        include:
          - os: Ubuntu
            environment-file: ci/requirements-linux.yml
            shell: bash -l {0}
          # - os: macOS
          #   environment-file: ci/requirements-macos.yml
          #   shell: bash -l {0}
          - os: Windows
            environment-file: ci/requirements-windows.yml
            shell: powershell

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          channel-priority: strict
          activate-environment: rrtmg_build_env
          auto-update-conda: false
          python-version: ${{ matrix.python-version }}
          environment-file: ${{ matrix.environment-file }}
          mamba-version: '*'
          use-mamba: true

      - name: Setup Fortran compiler for Windows
        if: ${{ matrix.os == 'Windows' }}
        run: |
          echo "[build]`ncompiler=mingw32" | Out-File -Encoding ASCII ~/pydistutils.cfg
      - name: Build and install climlab
        run: |
          python -m pip install --no-deps --editable . -vv
      - name: Import climlab
        run: |
          python -c "from climlab_rrtmg import rrtmg_lw, rrtmg_sw"
      - name: Run tests
        run: |
          python -m pytest --verbose
